[project]
name = "repro"
version = "0.1.0"
description = ""
authors = [
    {name = "Luca Muscat"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dummy @ file:../dummy"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
